version: '3.1'

services:

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:adminpass@mongo:27017/production?authSource=admin

  mongo:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - '27017:27017'

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpass
      MONGO_INITDB_DATABASE: production
